#!/usr/bin/env python 

import os, sys, argparse

CMDINFO = {
    'help': 'Print top level help',
    'cmd' : 'Prints the available commands',
    'check': 'Check integrity of the config file',
}

def top_level_help():
    print "Usage: {0} <command> <command args>".format(sys.argv[0])
    print "See '{0} cmd' to see the available commands".format(sys.argv[0])

def cmd_cmd():
    print "Available commands:"
    for cmd, info in CMDINFO.iteritems():
        print "{0:10} {1}".format(cmd, info)

def check_cmd(args):
    if len(args) < 1:
        print "Error: not enough arguments"
        print "Usage: {0} check <config file>"
        sys.exit(1)

    cfgfile = args[0]

    import yaml
    from pprint import pprint
    with open(cfgfile) as f:
        y = yaml.load(f)
        pprint(y)



def dispatch_cmd(cmd, args):
    if cmd == 'help':
        top_level_help()
    elif cmd == 'cmd':
        cmd_cmd()
    elif cmd == 'check':
        check_cmd(args)
    else:
        print "Error: unknown command [{0}]".format(cmd)
        top_level_help()
        sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv[1:]) < 1:
        print "Error: not enough arguments"
        top_level_help()
        sys.exit(1)


    cmd, args = sys.argv[1], sys.argv[2:]

    dispatch_cmd(cmd, args)


    
