#!/usr/bin/env python

import sys
import logging

log = logging.getLogger()

def usage():
    print "Usage: {0} <command>".format(sys.argv[0])
    print "   command = help|run"


def run_help():
    print "Usage: {0} run <config file> <type> <test/suitename> [args]"
    print "    type: step|test|suite"


def parse_cli(args):
    if len(args) < 1:
        usage()
        sys.exit(1)


    cmd, args = args[0], args[1:]

    if cmd == "help":
        usage()
        return
    elif cmd == "run":
        if len(args) == 0 or args[0] == "help" or len(args) < 3:
            run_help()
            sys.exit(1)


        cfgfile, runtype, entityname, args = args[0], args[1], args[2], args[2:]
        if runtype not in ['step', 'test', 'suite']:
            print "Error: runtype [%s] not valid" % runtype
            sys.exit(1)




if __name__ == '__main__':
    parse_cli(sys.argv[1:])
